CREATE DATABASE zzDB_SISTEMA_CINEMA
ON PRIMARY(
NAME=zzDB_SISTEMA_CINEMA,
FILENAME='D:\3 - Visual Studio\0 - Projetos VisualStudio\SistemaCinema\zzDB_SISTEMA_CINEMA.mdf',
SIZE=10MB,
MAXSIZE=30MB,
FILEGROWTH=2%
)
GO

USE zzDB_SISTEMA_CINEMA
GO

CREATE TABLE BLT_00(
BLT_CODIGO INT PRIMARY KEY IDENTITY(1,1),
BLT_FILME VARCHAR(100) NOT NULL,
BLT_GENERO VARCHAR(50) NOT NULL,
BLT_LINGUAGEM VARCHAR(20) NOT NULL,
BLT_AUTOR VARCHAR(30) NOT NULL,
BLT_VALOR MONEY NOT NULL,
BLT_HORARIO TIME NOT NULL,
BLT_DATA DATE NOT NULL,
BLT_DISPONIBILIDADE SMALLINT NOT NULL,
BLT_SALA SMALLINT NOT NULL,
BLT_ENCARTE IMAGE
)
GO

SELECT * FROM BLT_00 
GO