CREATE DATABASE dbSystemPizzaria
ON PRIMARY(
NAME = dbSystemPizzaria,
FILENAME = 'C:\BD\dbSystemPizzaria.MDF',
SIZE = 10MB,
MAXSIZE = 30MB,
FILEGROWTH = 10%);

USE dbSystemPizzaria;

CREATE TABLE TBL_CLIENTES
(
        CLI_ID INT PRIMARY KEY IDENTITY(1000,1),
        CLI_TELEFONE VARCHAR(15) NOT NULL,
        CLI_NOME VARCHAR(200) NOT NULL,
        CLI_CEP VARCHAR(9) NOT NULL,
        CLI_LOGRADOURO VARCHAR(100) NOT NULL,
        CLI_BAIRRO VARCHAR(50) NOT NULL,
        CLI_PONTOREFERENCIA VARCHAR(200) NOT NULL,
        CLI_PERCENTUALENCARGOS FLOAT NOT NULL,
        CLI_CONCEDERDESCONTONOPRECO BIT NOT NULL
);

--SELECT * FROM TBL_CLIENTES;